{% set name = "windpowerlib" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/windpowerlib-{{ version }}.tar.gz
  sha256: f61a31569c90fa97dab42bf81af6526d8d36eda3b56b4f9b1d5bdf126ae14224

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas >=0.20.0
    - python >=3.6
    - numpy
    - requests

test:
  imports:
    - windpowerlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/wind-python/windpowerlib
  summary: Creating time series of wind power plants.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kyri-petrou
